Lejla weekly task
donnellreuben/Coding-Tasks-B37GR2 pull request #7
Opened 2024-11-14 17:35 UTC by Lejlam7

My solution.

2024-11-14 17:55 UTC, donnellreuben requested changes
Is your solution in the correct folder?

I see:
src/Week01Tasks/OddOrEven

When I should see:
src/lejlaWeeklyTasks/OddOrEven

2024-11-14 18:44 UTC, raminka07 requested changes
yeah, same as Donnell's question. is it not in your own package?

2024-11-14 19:14 UTC, Lejlam7 commented
Not sure. On my end I see the solution on here.

2024-11-21 13:11 UTC, TroyYC approved these changes

2024-11-21 13:11 UTC, merged